name: Deploy Vite Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer SSH Agent
      - name: Configure SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Étape 3 : Mettre à jour known_hosts
      - name: Update known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # Étape 4 : Créer le répertoire distant
      - name: Create remote directory
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /tmp/deploy/"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Étape 5 : Envoyer les fichiers générés
      - name: Upload files to server
        run: scp -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/tmp/deploy/

      - name: delete if exists
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo rm -rf /var/www/html/pokemon"

      # Étape 6 : Déplacer les fichiers
      - name: Move files to the correct location
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "sudo mv /tmp/deploy/* /var/www/html/pokemon"

      # Étape 7 : Créer le fichier .env
      - name: go in directory
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/html/pokemon"

      - name: create environment file
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'NODE_ENV=dev' > .env"

      - name: add env api url
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'VITE_API_URL=${{ secrets.VITE_API_URL }}' >> .env"
        
      - name: add env api key
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'VITE_API_KEY=${{ secrets.VITE_API_KEY }}' >> .env"
       
      - name: add env api limit
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'VITE_API_LIMIT=${{ secrets.VITE_API_LIMIT }}' >> .env"