name: Deploy Vite Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer SSH Agent
      - name: Configure SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Étape 3 : Mettre à jour known_hosts
      - name: Update known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Étape 5 : Build le projet Vite
      - name: Install dependencies and build project
        run: npm run build

      # Étape 5 : Créer le répertoire distant
      - name: Create remote directory
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /tmp/deploy/"

      # Étape 6 : Envoyer les fichiers générés
      - name: Upload files to server
        run: scp -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/tmp/deploy/

      # Étape 7 : Déployer les fichiers au bon endroit
      - name: Move files to the correct location
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            sudo mv /tmp/deploy/* /var/www/pokemon/
            sudo systemctl reload nginx
          EOF
