name: Exercice 1

on: 
  push:
    branches:
      - '**'

jobs:
  display-message:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name : installation node
      uses: actions/setup-node@v4

    - name: clean install
      run: npm ci

    - name: prettier check
      run: npx prettier . --check

    - name: lint
      run: npm run lint

    - name: message
      run: echo "A push event has been triggered!"