name: Exo

on: 
  push:
    branches:
      - '**'

jobs:
  test-for-production:
    runs-on: ubuntu-latest

    steps:
      env:
        CI: true
        NODE_ENV: production
        PORT: 5173
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        VITE_API_LIMIT: ${{ secrets.VITE_API_LIMIT }}

    # 1. Message pour notifier le déclenchement de l'action
    - name: message
      run: echo "A push event has been triggered!"

    # 2. Checkout du dépôt
    - name: checkout repo
      uses: actions/checkout@v4

    # 3. Installation de Node.js
    - name : installation node
      uses: actions/setup-node@v4

    # 4. Installation des dépendances
    - name: clean install
      run: npm ci

    # 5. Vérification Prettier
    - name: prettier check
      run: npx prettier . --check

    # 6. Linter (ESLint)
    - name: lint
      run: npm run lint

    # 7. Vérification des types avec TypeScript
    - name: type check
      run: npx tsc --noEmit

    # 8. Build du projet
    - name: build
      run: npm run build

    # 9. Run le projet
    - name: run in background
      run: npm run dev &

    # 10. Wait for the server to start
    - name: wait for server
      run: npx wait-on http://localhost:5173

    # 9. Exécution des tests Cypress
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        record: false # Si vous n'utilisez pas le Dashboard Cypress

    # 10. Enregistrement des artefacts Cypress - Screenshots (en cas d'échec)
    - name: Upload Cypress Screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        if-no-files-found: ignore # Ignore si aucun fichier n'est trouvé

    # 11. Enregistrement des artefacts Cypress - Vidéos
    - name: Upload Cypress Videos
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos
        if-no-files-found: ignore # Ignore si aucun fichier n'est trouvé