name: Exo

on: 
  push:
    branches:
      - '**'

jobs:
  test-for-production:
    runs-on: ubuntu-latest

    steps:

    - name: message
      run: echo "A push event has been triggered!"

    - name: checkout repo
      uses: actions/checkout@v4

    - name : installation node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - name: clean install
      run: npm ci

    - name: prettier check
      run: npx prettier . --check

    - name: lint
      run: npm run lint

    - name: type check
      run: npx tsc --noEmit

    - name: build
      run: npm run build
      
    - name: Checkout
        uses: actions/checkout@v4# Install npm dependencies, cache them correctly# and run all Cypress tests

    - name: Cypress run
        uses: cypress-io/github-action@v6